blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/UPENN-PNGC/discussions
    about: Ask questions or start discussions with the community
  - name: Security Issue
    url: https://github.com/UPENN-PNGC/.github/blob/main/SECURITY.md
    about: Report security vulnerabilities privately
